language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: deploy
env:
  global:
  - secure: In5DrRyLCmbGM30K43T4v6ZJ/OUATknxy6B3aGxV3jUJZ34emTYlAQlQti2slIQGzisOTsTXSAlclavJm/UrmuiTpJJfeePiCFBaoFtVWu0NVGbzvT74yd+1YzpQGojwrxDx6e8zFIvJclV36dXv3C+qOo1rP+qVEFyv1cmFmg9/RtQ5SrFeZ8A7CI5Ma7MvjyXF/VAekoogiV3MJreJzupWMjXUroMqT2AJzfmN5QsGhsI0NIsrj8Vh2gCYKjyY3cvaVHae1MW5xrj9EeGOtLlHuMDpTWEpMjDggMZwxven/V83tM0cheAR4y252TMWUDLXgC9qbthNDleIa7B/VipsVx7mplyTuRp5RJNpjyuq5eu/d0/maMkOiEGh0nfVWHwiDZADNfQDzdgt4pqUH/yuiLovVJ9BPpNsvWktSKjVfTh3+8OJmhuDLIMAnh1+HvThBGf33YV6KODzoaGvCMet4AjPgU0xTncfpICpj7fK72+BU5BRrr4PMrig0E96FM1onvWNeY/0jgQTABGWfsQBX9VPN5y4X4EtiM7jBt1TxOSjJiRvQ6Jy3QvlpVVgFPUDaQbnwtEwGiGH7U5sra0A/qMGcDl1uQ+rvNP0Damr+6oyanBCfPNZTNGmXKQBI1D2sx13zFbgMAlzRVeUfMu316PwV2/k6U2YyQbDOAY=
  - secure: gFkGUqqUKRKW4y01/ry3pDudgngg+/UaeSqwgdLXq0QsjwOl26YS5uYaB1ikF3bFqKK7oXAcQQcPfBqIidU/QiWQ7TfC07RZmOyEuBpd/v+XGfSCIDtcfW+ChjSCrfSY9ij0vjFRdVcj0npHfybFjT5uZrvbWsJjFa/29KYUTIv7fXXJGSk6yWdrl82hGxPJROrGHwcByrHKoFWqHXM3Ujqcw5Nq/EGf0AHH2Bvi1CEFgig64KMWbp36gkmcTG6dfCyxDZ4MTsRkRzKrHNDXCfK57QB8O93YAO8qcyx9eSks5VH1rAQ4vRjHm9MXO6qpzifhP1+OBzA7DxYCNkx1dz8GtV0ekdWCZfmGYwk2hfWgykdOwe33Ur237cUCEiZdbrn1gXGN4EMoG41V6rLIUUtu08meCgJsA6ls+UX2NZuiWbUoezLXBfepaYn3bIse+W7+Ff92v5zbpjbOrc+xCvkF4tzUxZGkZAc79GvUFj5fIDAm++TVNRYcr7oxcjrrPo21u5o50NN+KipZAiA2an5ZrGfi5TCaLVUwZ92hV6bGxdrCxEp202xQLbYbVbbgGoYOQGHT0zsNUMxPt6thpRM7HF3aH8JrLr3ZZ8VKY199EHxcneGYe1y4Fx9Ii10tFQWHRS8nvbJzP5MeCr9MAwnrIRa6DX4vdtxZ2nLCYBY=
